### ISSUE TITLE
problem with card installation

### ISSUE THREAD

**Issue by arek156** [ledhed-jgh/Vindriktning-Card#1]
Hi
I'm trying to install the card, but I have a problem, I don't know what the entity is: entity: sensor.vindriktning_color
Can you tell me how to create it because it is not an entity from the sensor but some kind of color control

**Comment by ledhed-jgh** [comment]
My apologies, I forgot to add the code for the template sensor. I'll include it when I get home tonight.

**Comment by ledhed-jgh** [comment]
template sensor code added to Readme.

**Comment by arek156** [comment]
thank you
